import { User, Lead, Order, Operation, RawFootage, Production, Payment, ActivityLog, Equipment } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'U-001',
    name: 'Rupand Das',
    mobile: '+1 (555) 019-2834',
    email: 'rupandas8811@gmail.com',
    role: 'Business Owner',
    active: true,
    created_at: '2026-05-01T08:00:00Z',
    password: 'owner123'
  },
  {
    id: 'U-002',
    name: 'Sarah Jenkins',
    mobile: '+1 (555) 014-9988',
    email: 'sarah.j@photocrew.com',
    role: 'Sales Team',
    active: true,
    created_at: '2026-05-02T09:30:00Z',
    password: 'sales123'
  },
  {
    id: 'U-003',
    name: 'Robert O\'Connor',
    mobile: '+1 (555) 016-5544',
    email: 'robert.o@photocrew.com',
    role: 'Operations Team',
    active: true,
    created_at: '2026-05-03T10:15:00Z',
    password: 'ops123'
  },
  {
    id: 'U-004',
    name: 'Emily Watson',
    mobile: '+1 (555) 012-3322',
    email: 'emily.w@photocrew.com',
    role: 'Production Team',
    active: true,
    created_at: '2026-05-04T11:00:00Z',
    password: 'prod123'
  },
  {
    id: 'U-005',
    name: 'Demo Owner',
    mobile: '+919999999901',
    email: 'owner@demo.com',
    username: 'owner',
    role: 'Business Owner',
    active: true,
    created_at: '2026-06-12T00:00:00Z',
    password: 'demo123'
  },
  {
    id: 'U-006',
    name: 'Demo Sales',
    mobile: '+919999999902',
    email: 'sales@demo.com',
    username: 'sales',
    role: 'Sales Team',
    active: true,
    created_at: '2026-06-12T00:00:00Z',
    password: 'demo123'
  },
  {
    id: 'U-007',
    name: 'Demo Operations',
    mobile: '+919999999903',
    email: 'ops@demo.com',
    username: 'ops',
    role: 'Operations Team',
    active: true,
    created_at: '2026-06-12T00:00:00Z',
    password: 'demo123'
  },
  {
    id: 'U-008',
    name: 'Demo Production',
    mobile: '+919999999904',
    email: 'prod@demo.com',
    username: 'prod',
    role: 'Production Team',
    active: true,
    created_at: '2026-06-12T00:00:00Z',
    password: 'demo123'
  },
  {
    id: 'U-009',
    name: 'Business Owner Demo',
    mobile: '+919999999909',
    email: 'owner@photocrewdemo.com',
    username: 'businessowner',
    role: 'Business Owner',
    active: true,
    created_at: '2026-06-14T00:00:00Z',
    password: 'Admin@123'
  },
  {
    id: 'U-010',
    name: 'Sales Team Demo',
    mobile: '+919999999910',
    email: 'sales@photocrewdemo.com',
    username: 'salesteam',
    role: 'Sales Team',
    active: true,
    created_at: '2026-06-14T00:00:00Z',
    password: 'Sales@123'
  },
  {
    id: 'U-011',
    name: 'Operations Team Demo',
    mobile: '+919999999911',
    email: 'operations@photocrewdemo.com',
    username: 'operationsteam',
    role: 'Operations Team',
    active: true,
    created_at: '2026-06-14T00:00:00Z',
    password: 'Ops@123'
  },
  {
    id: 'U-012',
    name: 'Production Team Demo',
    mobile: '+919999999912',
    email: 'production@photocrewdemo.com',
    username: 'productionteam',
    role: 'Production Team',
    active: true,
    created_at: '2026-06-14T00:00:00Z',
    password: 'Prod@123'
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    lead_id: 'LD-9001',
    created_date: '2026-06-10',
    lead_source: 'Instagram',
    customer_name: 'Sophia Loren',
    mobile: '+1 (555) 123-4567',
    email: 'sophia@example.com',
    event_type: 'Wedding Shoot',
    event_date: '2026-08-15',
    event_time: '14:00',
    event_location: 'Grand Hyatt Beach Lawn',
    budget: 5500,
    sales_person: 'Sarah Jenkins',
    status: 'New Lead',
    remarks: 'Inquired via Instagram DM. Wants premium cinematic style with 2 videographers.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9002',
    created_date: '2026-06-09',
    lead_source: 'Website Form',
    customer_name: 'Arthur Pendragon',
    mobile: '+1 (555) 987-6543',
    email: 'arthur@royal.co',
    event_type: 'Corporate Event',
    event_date: '2026-07-22',
    event_time: '09:00',
    event_location: 'Camelot Conference Hall',
    budget: 3500,
    sales_person: 'Sarah Jenkins',
    status: 'Follow Up',
    remarks: 'Followed up on email. Client checking options. Scheduled next call for next week.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9003',
    created_date: '2026-06-05',
    lead_source: 'Referral',
    customer_name: 'Liam Neeson',
    mobile: '+1 (555) 443-8822',
    email: 'liam@taken.net',
    event_type: 'Birthday Banquet',
    event_date: '2026-06-28',
    event_time: '18:00',
    event_location: 'Starlight Ballroom Resort',
    budget: 2200,
    sales_person: 'Sarah Jenkins',
    status: 'Quotation Sent',
    remarks: 'Sent quotation of $2,100 including drone photography. Waiting for approval.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9004',
    created_date: '2026-06-02',
    lead_source: 'Facebook Ad',
    customer_name: 'Helena Carter',
    mobile: '+1 (555) 777-1122',
    email: 'helena@star.com',
    event_type: 'Fashion Portfolio',
    event_date: '2026-07-05',
    event_time: '11:00',
    event_location: 'Industrial Warehouse Studio B',
    budget: 1800,
    sales_person: 'Sarah Jenkins',
    status: 'Negotiation',
    remarks: 'Negotiating discount. They requested $1,500 budget. Might close at $1,650.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9005',
    created_date: '2026-05-18',
    lead_source: 'Instagram',
    customer_name: 'Victoria & Albert',
    mobile: '+1 (555) 434-2211',
    email: 'royal@wedding.org',
    event_type: 'Destination Wedding',
    event_date: '2026-09-01',
    event_time: '16:00',
    event_location: 'Udaipur Palace Resort',
    budget: 12500,
    sales_person: 'Sarah Jenkins',
    status: 'Order Confirmed',
    remarks: 'Order confirmed with 50% advance. Moving to operations stage.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9006',
    created_date: '2026-05-15',
    lead_source: 'Website Form',
    customer_name: 'Marcus Aurelius',
    mobile: '+1 (555) 880-9988',
    email: 'marcus@philosophy.edu',
    event_type: 'Pre-Wedding Shoot',
    event_date: '2026-06-20',
    event_time: '06:00',
    event_location: 'Sunrise Mountain Peak',
    budget: 3200,
    sales_person: 'Sarah Jenkins',
    status: 'Operations Assigned',
    remarks: 'Drone pre-flight authorized. Crew allocated and equipment kit prepped.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9007',
    created_date: '2026-05-10',
    lead_source: 'Referral',
    customer_name: 'Billie Eilish',
    mobile: '+1 (555) 111-2222',
    email: 'billie@interscope.com',
    event_type: 'Music Video Launch',
    event_date: '2026-06-08',
    event_time: '20:00',
    event_location: 'Underground Concrete Tunnel',
    budget: 8000,
    sales_person: 'Sarah Jenkins',
    status: 'Event Completed',
    remarks: 'Shoot completed successfully. Incredible slow-mo shots captured. Raw footage pending transfer.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9008',
    created_date: '2026-05-08',
    lead_source: 'Google Search',
    customer_name: 'Elizabeth Bennet',
    mobile: '+1 (555) 666-4444',
    email: 'elizabeth@pemberley.com',
    event_type: 'Graduation Gala',
    event_date: '2026-06-03',
    event_time: '17:00',
    event_location: 'Longbourn Gardens',
    budget: 4500,
    sales_person: 'Sarah Jenkins',
    status: 'Editing Started',
    remarks: 'Footage received. Emily allocated as chief editor. Editing has started recursively.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9009',
    created_date: '2026-05-02',
    lead_source: 'Instagram',
    customer_name: 'Elon Musk',
    mobile: '+1 (555) 420-6969',
    email: 'elon@spacex.com',
    event_type: 'Product Commercial',
    event_date: '2026-05-25',
    event_time: '12:00',
    event_location: 'Starbase Launch Pad A',
    budget: 15000,
    sales_person: 'Sarah Jenkins',
    status: 'Customer Review',
    remarks: 'First cut sent. Waiting for review. Client loved the rocket booster framing.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9010',
    created_date: '2026-04-28',
    lead_source: 'Referral',
    customer_name: 'Bruce Wayne',
    mobile: '+1 (555) 911-3948',
    email: 'bruce@waynecorp.com',
    event_type: 'Charity Elite Gala',
    event_date: '2026-05-18',
    event_time: '19:00',
    event_location: 'Wayne Manor Ball Room',
    budget: 20000,
    sales_person: 'Sarah Jenkins',
    status: 'Delivered',
    remarks: 'Delivered final albums and prints. Payment pending confirmation.',
    created_by: 'Sarah Jenkins',
  },
  {
    lead_id: 'LD-9011',
    created_date: '2026-04-10',
    lead_source: 'Website Form',
    customer_name: 'Gerd Muller',
    mobile: '+1 (555) 711-2092',
    email: 'gerd@munich.de',
    event_type: 'Real Estate Reel',
    event_date: '2026-05-02',
    event_time: '15:00',
    event_location: 'Beverly Hills Mansion 304',
    budget: 2500,
    sales_person: 'Sarah Jenkins',
    status: 'Closed',
    remarks: 'Project successfully completed, fully paid, closed and archived in system.',
    created_by: 'Sarah Jenkins',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    order_id: 'ORD-1005',
    lead_id: 'LD-9005',
    customer_name: 'Victoria & Albert',
    mobile: '+1 (555) 434-2211',
    event_type: 'Destination Wedding',
    event_date: '2026-09-01',
    event_time: '16:00',
    event_location: 'Udaipur Palace Resort',
    package_name: 'Royal Destination Platinum',
    quotation_amount: 12500,
    advance_received: 6250,
    balance_amount: 6250,
    order_status: 'Confirmed',
    current_stage: 'Order Confirmed',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    order_id: 'ORD-1006',
    lead_id: 'LD-9006',
    customer_name: 'Marcus Aurelius',
    mobile: '+1 (555) 880-9988',
    event_type: 'Pre-Wedding Shoot',
    event_date: '2026-06-20',
    event_time: '06:00',
    event_location: 'Sunrise Mountain Peak',
    package_name: 'Scenic Pre-Wedding Gold',
    quotation_amount: 3200,
    advance_received: 1600,
    balance_amount: 1600,
    order_status: 'Confirmed',
    current_stage: 'Operations Assigned',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-02T11:30:00Z',
  },
  {
    order_id: 'ORD-1007',
    lead_id: 'LD-9007',
    customer_name: 'Billie Eilish',
    mobile: '+1 (555) 111-2222',
    event_type: 'Music Video Launch',
    event_date: '2026-06-08',
    event_time: '20:00',
    event_location: 'Underground Concrete Tunnel',
    package_name: 'Aesthetic Music Video Premium',
    quotation_amount: 8000,
    advance_received: 4000,
    balance_amount: 4000,
    order_status: 'Completed',
    current_stage: 'Event Completed',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-03T14:45:00Z',
  },
  {
    order_id: 'ORD-1008',
    lead_id: 'LD-9008',
    customer_name: 'Elizabeth Bennet',
    mobile: '+1 (555) 666-4444',
    event_type: 'Graduation Gala',
    event_date: '2026-06-03',
    event_time: '17:00',
    event_location: 'Longbourn Gardens',
    package_name: 'Estate Gala Cinematic',
    quotation_amount: 4500,
    advance_received: 2000,
    balance_amount: 2500,
    order_status: 'Completed',
    current_stage: 'Editing Started',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-04T09:12:00Z',
  },
  {
    order_id: 'ORD-1009',
    lead_id: 'LD-9009',
    customer_name: 'Elon Musk',
    mobile: '+1 (555) 420-6969',
    event_type: 'Product Commercial',
    event_date: '2026-05-25',
    event_time: '12:00',
    event_location: 'Starbase Launch Pad A',
    package_name: 'High Dynamic Advertising Video',
    quotation_amount: 15000,
    advance_received: 5000,
    balance_amount: 10000,
    order_status: 'Completed',
    current_stage: 'Customer Review',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-05T15:30:00Z',
  },
  {
    order_id: 'ORD-1010',
    lead_id: 'LD-9010',
    customer_name: 'Bruce Wayne',
    mobile: '+1 (555) 911-3948',
    event_type: 'Charity Elite Gala',
    event_date: '2026-05-18',
    event_time: '19:00',
    event_location: 'Wayne Manor Ball Room',
    package_name: 'Ultra Elite Grand Package',
    quotation_amount: 20000,
    advance_received: 10000,
    balance_amount: 10000,
    order_status: 'Delivered',
    current_stage: 'Delivered',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-06T16:00:00Z',
  },
  {
    order_id: 'ORD-1011',
    lead_id: 'LD-9011',
    customer_name: 'Gerd Muller',
    mobile: '+1 (555) 711-2092',
    event_type: 'Real Estate Reel',
    event_date: '2026-05-02',
    event_time: '15:00',
    event_location: 'Beverly Hills Mansion 304',
    package_name: 'Super High-Res Aerial Package',
    quotation_amount: 2500,
    advance_received: 2500,
    balance_amount: 0,
    order_status: 'Closed',
    current_stage: 'Closed',
    sales_person: 'Sarah Jenkins',
    created_at: '2026-06-07T11:00:00Z',
  }
];

export const INITIAL_OPERATIONS: Operation[] = [
  {
    operation_id: 'OP-5006',
    order_id: 'ORD-1006',
    photographer_assigned: 'Jack Richards',
    videographer_assigned: 'Tina Fey',
    drone_operator_assigned: 'Leo Di Caprio',
    assistant_assigned: 'Steve Rogers',
    equipment_kit: 'Kit Gold: Sony A7iv, RED Komodo, DJI Inspire 3 Drone',
    reporting_time: '04:30',
    event_status: 'Assigned',
    remarks: 'Requires warm outfits, peak gets freezing at sunrise.',
    updated_by: 'Robert O\'Connor',
  },
  {
    operation_id: 'OP-5007',
    order_id: 'ORD-1007',
    photographer_assigned: 'Clint Barton',
    videographer_assigned: 'Natasha Romanoff',
    drone_operator_assigned: 'Tony Stark',
    assistant_assigned: 'Peter Parker',
    equipment_kit: 'Kit Tunnel: ARRI Alexa Mini, Leica Cine Primes, low-light gimbals',
    reporting_time: '18:30',
    event_status: 'Completed',
    remarks: 'Shoot executed flawlessly. Tunnel dust required dry-mount dust bags for rigs.',
    updated_by: 'Robert O\'Connor',
  },
  {
    operation_id: 'OP-5008',
    order_id: 'ORD-1008',
    photographer_assigned: 'Wanda Maximoff',
    videographer_assigned: 'Vision',
    drone_operator_assigned: 'None',
    assistant_assigned: 'Sam Wilson',
    equipment_kit: 'Kit Garden: Canon R5, Ronin S3 Gimbal, Apure Light panels',
    reporting_time: '15:30',
    event_status: 'Completed',
    remarks: 'Overcast light was highly favorable. Did not need dense diffusion scrims.',
    updated_by: 'Robert O\'Connor',
  },
  {
    operation_id: 'OP-5009',
    order_id: 'ORD-1009',
    photographer_assigned: 'Bruce Banner',
    videographer_assigned: 'Thor Odinson',
    drone_operator_assigned: 'Tony Stark',
    assistant_assigned: 'Steve Rogers',
    equipment_kit: 'Kit Industrial: Phantom Flex 4K High-Speed, heavy duty robotic track',
    reporting_time: '10:00',
    event_status: 'Completed',
    remarks: 'High security clearance checked. Footage stored on encrypted drives.',
    updated_by: 'Robert O\'Connor',
  },
  {
    operation_id: 'OP-5010',
    order_id: 'ORD-1010',
    photographer_assigned: 'Peter Parker',
    videographer_assigned: 'Miles Morales',
    drone_operator_assigned: 'Tony Stark',
    assistant_assigned: 'Gwen Stacy',
    equipment_kit: 'Kit Elegance: Hasselblad H6D, 3x Studio Strobe flash units',
    reporting_time: '17:00',
    event_status: 'Completed',
    remarks: 'Strict black tie compliance enforced on crew.',
    updated_by: 'Robert O\'Connor',
  },
  {
    operation_id: 'OP-5011',
    order_id: 'ORD-1011',
    photographer_assigned: 'Scott Lang',
    videographer_assigned: 'Steve Rogers',
    drone_operator_assigned: 'Sam Wilson',
    assistant_assigned: 'None',
    equipment_kit: 'Kit Compact DSLR + DJI Mavic 3 Pro',
    reporting_time: '14:00',
    event_status: 'Completed',
    remarks: 'Sunny afternoon skylight worked perfectly.',
    updated_by: 'Robert O\'Connor',
  }
];

export const INITIAL_RAW_FOOTAGE: RawFootage[] = [
  {
    tracking_id: 'TRK-2007',
    order_id: 'ORD-1007',
    event_completed_date: '2026-06-08',
    raw_received: true,
    server_path: 's3://photocrew-vault-production/2026/billie-tunnel-mv/raw/',
    uploaded_by: 'Natasha Romanoff',
    uploaded_date: '2026-06-09T02:00:00Z',
    status: 'Received',
  },
  {
    tracking_id: 'TRK-2008',
    order_id: 'ORD-1008',
    event_completed_date: '2026-06-03',
    raw_received: true,
    server_path: 's3://photocrew-vault-production/2026/bennet-graduation/raw/',
    uploaded_by: 'Vision',
    uploaded_date: '2026-06-04T07:15:00Z',
    status: 'Received',
  },
  {
    tracking_id: 'TRK-2009',
    order_id: 'ORD-1009',
    event_completed_date: '2026-05-25',
    raw_received: true,
    server_path: 's3://photocrew-vault-production/2026/spacex-starbase-ad/raw/',
    uploaded_by: 'Thor Odinson',
    uploaded_date: '2026-05-26T11:00:00Z',
    status: 'Received',
  },
  {
    tracking_id: 'TRK-2010',
    order_id: 'ORD-1010',
    event_completed_date: '2026-05-18',
    raw_received: true,
    server_path: 's3://photocrew-vault-production/2026/wayne-gala/raw/',
    uploaded_by: 'Miles Morales',
    uploaded_date: '2026-05-19T01:30:00Z',
    status: 'Received',
  },
  {
    tracking_id: 'TRK-2011',
    order_id: 'ORD-1011',
    event_completed_date: '2026-05-02',
    raw_received: true,
    server_path: 's3://photocrew-vault-production/2026/muller-mansion/raw/',
    uploaded_by: 'Steve Rogers',
    uploaded_date: '2026-05-02T19:00:00Z',
    status: 'Received',
  }
];

export const INITIAL_PRODUCTION: Production[] = [
  {
    production_id: 'PRD-4008',
    tracking_id: 'TRK-2008',
    editor_assigned: 'Emily Watson',
    raw_footage_location: 's3://photocrew-vault-production/2026/bennet-graduation/raw/',
    editing_start_date: '2026-06-05',
    expected_delivery_date: '2026-06-25',
    editing_status: 'Editing In Progress',
    customer_review_status: undefined,
    remarks: 'Color grading started in DaVinci Resolve. Wedding cinematic LUTs applied.',
  },
  {
    production_id: 'PRD-4009',
    tracking_id: 'TRK-2009',
    editor_assigned: 'Dennis Nedry',
    raw_footage_location: 's3://photocrew-vault-production/2026/spacex-starbase-ad/raw/',
    editing_start_date: '2026-05-28',
    expected_delivery_date: '2026-06-15',
    editing_status: 'Client Review Sent',
    customer_review_status: 'Pending Review',
    remarks: 'Draft 1 exported in 1080p and uploaded for review. Ready to receive client feedback.',
  },
  {
    production_id: 'PRD-4010',
    tracking_id: 'TRK-2010',
    editor_assigned: 'Emily Watson',
    raw_footage_location: 's3://photocrew-vault-production/2026/wayne-gala/raw/',
    editing_start_date: '2026-05-20',
    expected_delivery_date: '2026-06-01',
    editing_status: 'Project Delivered',
    customer_review_status: 'Approved',
    delivery_date: '2026-06-01',
    remarks: 'Delivered in ultra-high resolution 4K ProRes 422 HQ via physical secure drive.',
  },
  {
    production_id: 'PRD-4011',
    tracking_id: 'TRK-2011',
    editor_assigned: 'Jimmy Woo',
    raw_footage_location: 's3://photocrew-vault-production/2026/muller-mansion/raw/',
    editing_start_date: '2026-05-03',
    expected_delivery_date: '2026-05-08',
    editing_status: 'Project Delivered',
    customer_review_status: 'Approved',
    delivery_date: '2026-05-08',
    remarks: 'Reels optimized for Instagram and YouTube shorts delivered. Highly satisfied.',
  }
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    payment_id: 'PAY-3005',
    order_id: 'ORD-1005',
    quotation_amount: 12500,
    advance_received: 6250,
    balance_due: 6250,
    final_payment_received: 0,
    payment_status: 'Partially Paid',
  },
  {
    payment_id: 'PAY-3006',
    order_id: 'ORD-1006',
    quotation_amount: 3200,
    advance_received: 1600,
    balance_due: 1600,
    final_payment_received: 0,
    payment_status: 'Partially Paid',
  },
  {
    payment_id: 'PAY-3007',
    order_id: 'ORD-1007',
    quotation_amount: 8000,
    advance_received: 4000,
    balance_due: 4000,
    final_payment_received: 0,
    payment_status: 'Partially Paid',
  },
  {
    payment_id: 'PAY-3008',
    order_id: 'ORD-1008',
    quotation_amount: 4500,
    advance_received: 2000,
    balance_due: 2500,
    final_payment_received: 0,
    payment_status: 'Partially Paid',
  },
  {
    payment_id: 'PAY-3009',
    order_id: 'ORD-1009',
    quotation_amount: 15000,
    advance_received: 5000,
    balance_due: 10000,
    final_payment_received: 0,
    payment_status: 'Partially Paid',
  },
  {
    payment_id: 'PAY-3010',
    order_id: 'ORD-1010',
    quotation_amount: 20000,
    advance_received: 10000,
    balance_due: 10000,
    final_payment_received: 0,
    payment_date: undefined,
    payment_status: 'Partially Paid', // payment pending
  },
  {
    payment_id: 'PAY-3011',
    order_id: 'ORD-1011',
    quotation_amount: 2500,
    advance_received: 2500,
    balance_due: 0,
    final_payment_received: 0,
    payment_date: '2026-05-02',
    payment_proof_url: 'https://photocrew-receipts.s3.amazonaws.com/rec-31942.pdf',
    payment_status: 'Fully Paid',
  }
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    log_id: 'LOG-001',
    user_name: 'Sarah Jenkins',
    role: 'Sales Team',
    action: 'Created New Lead',
    module: 'Sales',
    record_id: 'LD-9001',
    timestamp: '2026-06-10T05:00:00Z',
  },
  {
    log_id: 'LOG-002',
    user_name: 'Sarah Jenkins',
    role: 'Sales Team',
    action: 'Updated Follow-Up Status',
    module: 'Sales',
    record_id: 'LD-9002',
    timestamp: '2026-06-09T14:30:00Z',
  },
  {
    log_id: 'LOG-003',
    user_name: 'Robert O\'Connor',
    role: 'Operations Team',
    action: 'Assigned Crew to Order',
    module: 'Operations',
    record_id: 'ORD-1006',
    timestamp: '2026-06-02T11:45:00Z',
  },
  {
    log_id: 'LOG-004',
    user_name: 'Emily Watson',
    role: 'Production Team',
    action: 'Started Editing Project',
    module: 'Production',
    record_id: 'PRD-4008',
    timestamp: '2026-06-05T09:30:00Z',
  },
  {
    log_id: 'LOG-005',
    user_name: 'Rupand Das',
    role: 'Business Owner',
    action: 'Reviewed CEO Dashboard',
    module: 'Admin',
    record_id: 'ALL',
    timestamp: '2026-06-10T05:05:00Z',
  }
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    equipment_id: 'EQ-001',
    name: 'Sony FE 24-70mm f/2.8 GM II',
    type: 'Lens',
    brand: 'Sony',
    model: 'SEL2470GM2',
    serial_number: 'SN-SNY-289410',
    quantity: 3,
    status: 'Available',
    purchase_date: '2025-01-10',
    notes: 'Premium standard zoom lens. Extremely sharp.'
  },
  {
    equipment_id: 'EQ-002',
    name: 'Sony Alpha 7 IV Cinema Rig',
    type: 'Camera',
    brand: 'Sony',
    model: 'ILCE-7M4',
    serial_number: 'SN-SNY-902148',
    quantity: 2,
    status: 'Assigned',
    purchase_date: '2025-03-24',
    notes: 'Primary full-frame hybrid camera with Ronin baseplate.'
  },
  {
    equipment_id: 'EQ-003',
    name: 'RED Komodo 6K Starter Pack',
    type: 'Camera',
    brand: 'RED',
    model: 'Komodo-6K',
    serial_number: 'SN-RED-112093',
    quantity: 1,
    status: 'In Use',
    purchase_date: '2024-11-15',
    notes: 'High-end cinema camera for extreme resolutions and grading.'
  },
  {
    equipment_id: 'EQ-004',
    name: 'DJI Mavic 3 Pro Cine Premium',
    type: 'Drone',
    brand: 'DJI',
    model: 'Mavic-3-Cine',
    serial_number: 'SN-DJI-503928',
    quantity: 1,
    status: 'Available',
    purchase_date: '2025-05-02',
    notes: 'Tri-camera drone with Apple ProRes rendering.'
  },
  {
    equipment_id: 'EQ-005',
    name: 'Aputure LS 600d Pro Light',
    type: 'Light',
    brand: 'Aputure',
    model: 'LS-600D',
    serial_number: 'SN-APT-748921',
    quantity: 2,
    status: 'Under Maintenance',
    purchase_date: '2024-08-14',
    notes: 'Very high brightness LED spotlight. Power supply replacement pending.'
  },
  {
    equipment_id: 'EQ-006',
    name: 'Sennheiser AVX-835 Wireless Mic',
    type: 'Audio Equipment',
    brand: 'Sennheiser',
    model: 'AVX-835-SET',
    serial_number: 'SN-SEN-419082',
    quantity: 4,
    status: 'Available',
    purchase_date: '2025-02-18',
    notes: 'Wireless cardioid vocal mic, direct camera receiver.'
  },
  {
    equipment_id: 'EQ-007',
    name: 'SanDisk Professional 512GB CFexpress',
    type: 'Memory Cards',
    brand: 'SanDisk',
    model: 'CFX-B-512G',
    serial_number: 'SN-SND-100234',
    quantity: 8,
    status: 'Available',
    purchase_date: '2025-04-10',
    notes: 'Type B extreme high-speed media card for RED and Nikon.'
  }
];

